# Generated by Django 4.2 on 2023-04-18 11:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vendor_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default=1, upload_to=core.models.user_directory_path),
            preserve_default=False,
        ),
    ]
