# Generated by Django 4.2 on 2023-05-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(default='cash on delivery', max_length=255, null=True),
        ),
    ]
