# Generated by Django 4.2 on 2023-05-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cartorder_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on delivery'), ('paypal', 'Paypal Payment')], default='cod', max_length=255, null=True),
        ),
    ]
