# Generated by Django 4.2 on 2023-05-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_cartorder_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='days_return',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='warranty_period',
        ),
        migrations.AddField(
            model_name='product',
            name='days_return',
            field=models.CharField(default='100', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_period',
            field=models.CharField(default='100', max_length=100, null=True),
        ),
    ]
