# Generated by Django 4.2 on 2023-05-06 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_vendor_days_return_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='cover_image',
        ),
    ]
