# Generated by Django 4.2 on 2023-05-09 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_vendororder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorOrder',
        ),
    ]
